(1)

In [3]:
tinggi = [280, 215, 210,210,188,176,209,200]

In [4]:
import numpy as np

In [5]:
np_tinggi = np.array(tinggi)

In [6]:
np_tinggi

array([280, 215, 210, 210, 188, 176, 209, 200])

In [7]:
type(np_tinggi)

numpy.ndarray

(2)

In [8]:
np_tinggim= np_tinggi/100 #satuan meter harus dibagi 100

In [9]:
np_tinggim

array([2.8 , 2.15, 2.1 , 2.1 , 1.88, 1.76, 2.09, 2.  ])


(3)

In [10]:
berat = [88.5, 100, 98, 101, 78.3, 65.3, 109, 110]

In [11]:

np_berat = np.array(berat)

In [12]:
bmi = np_berat / np_tinggim ** 2

In [13]:
bmi

array([11.28826531, 21.63331531, 22.22222222, 22.90249433, 22.15368945,
       21.08083678, 24.95364117, 27.5       ])

(4)

In [14]:
bmi_tinggi = bmi > 23

In [15]:
bmi_tinggi

array([False, False, False, False, False, False,  True,  True])

In [16]:
bmi_tinggi[bmi > 23]

array([ True,  True])

(5)

B sama dengan soal

In [17]:
np.array([True,1,2]) + np.array([3,4, False])

array([4, 5, 2])

In [18]:
 A = np.array([True, 1,2, 3, 4, False])

In [19]:
A

array([1, 1, 2, 3, 4, 0])

In [20]:
B = np.array ([4,3,0]) + np.array([0,2,2])

In [21]:
B

array([4, 5, 2])

In [22]:
C = np.array([1,1,2])+np.array([3,4,-1])

In [23]:
C

array([4, 5, 1])

In [24]:
D = np.array([0,1,2,3,4,5])

In [25]:
D

array([0, 1, 2, 3, 4, 5])

(6)

In [26]:
np_berat[-1]

110.0

In [27]:
np_tinggi[3:8]

array([210, 188, 176, 209, 200])

(7)

In [28]:
pemain_basket = [[180,78.4], [215, 102.7], [210,98.5], [188, 75.2]]

In [29]:
basket_2d = np.array([[180,215,210,188], [78.4, 102.7, 98.5, 75.2]])

In [30]:
basket_2d

array([[180. , 215. , 210. , 188. ],
       [ 78.4, 102.7,  98.5,  75.2]])

In [31]:
type(basket_2d)

numpy.ndarray

In [32]:
basket_2d.shape

(2, 4)

(8)

In [33]:
basket_2d[0][0]

180.0

In [34]:
basket_2d[1][2]

98.5

(9)

In [35]:
np_mat = np.array([[1,2],
                 [3,4],
                 [5,6]])

In [36]:
print(np_mat*2)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [38]:
print(np_mat + np.array([10,10]))

[[11 12]
 [13 14]
 [15 16]]


In [39]:
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [41]:
print(basket_2d[1] + 5)


[ 83.4 107.7 103.5  80.2]


In [42]:
print(basket_2d[0]/100)

[1.8  2.15 2.1  1.88]


(10)

In [45]:
np.mean(np_tinggi)


211.0

In [46]:
np.median(np_tinggi)

209.5

(11)

In [59]:
#print tinggi dari basket_2d
rata_rata = np.mean(basket_2d[0])

In [54]:
type(rata_rata)

numpy.float64

In [56]:
Rata_rata1 = str(rata_rata)

In [58]:
print("Rata-Rata nya adalah" + Rata_rata1)

Rata-Rata 198.25


In [61]:
#print median dari tinggi basket_2d
median = np.median(basket_2d[0])

In [62]:
median1 = str(median)

In [63]:
print("median nya adalah " + median1)

median nya adalah 199.0


In [64]:
#print standart deviasi dari basket_2d
stddev = np.std(basket_2d[0])

In [65]:
stddev1 = str(stddev) 

In [66]:
print("standart deviasinya adalah " + stddev1)

standart deviasinya adalah 14.635146053251399


In [67]:
korelasi = np.corrcoef ( basket_2d[0], basket_2d[1])

In [68]:
korelasi


array([[1.        , 0.95865738],
       [0.95865738, 1.        ]])